### ISSUE TITLE
This plugins should set commentstring

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [towolf/vim-helm#10]
Hello

Currently, default Vim's `commentstring` is used, it's usually C-style comment `/* ... */`.

The plugin should set it to `{{/* ... */}}` - this will be a proper comment both for Go template and Yaml within Helm template or similar files.

**Comment by towolf** [comment]
If you are able to, please prepare a PR, then I'll add that.

**Comment by ievgenii-shepeliuk** [comment]
> If you are able to, please prepare a PR, then I'll add that.

I will provide a PR, but since I am not a `Vimscript` guru - it will probably require a facelift.
