### ISSUE TITLE
Readme file precision for .tpl file

### ISSUE THREAD

**Issue by SamuelTissot** [towolf/vim-helm#2]
Hello,

I wanted to do a small PR to add a little precision in the README file, for the new user. (but it seems you are not accepting PR?)

changed proposed
```
" set the .tpl file type to yaml to get basic syntax and indentation
autocmd BufNewFile,BufRead *.tpl   set filetype=yaml
" set the file type to helm to augment the syntax 
autocmd BufRead,BufNewFile */templates/*.yaml,*/templates/*.tpl set ft=helm
```

this way it would colorize the Helm `.tpl` files

thank you for your work

**Comment by towolf** [comment]
I don't accept pull requests?

I added `,*/templates/*.tpl` to the recommended autocommand. The other line should not be necessary since we are importing `yaml.vim` anyway in here https://github.com/towolf/vim-helm/blob/master/syntax/helm.vim#L15

**Comment by SamuelTissot** [comment]
Thanks, 

about
> I don't accept pull requests?
sorry, noop issue, my bad.
