### ISSUE TITLE
Bad compatibility with Oil file explorer

### ISSUE THREAD

**Issue by Drowze** [towolf/vim-helm#24]
[Oil](https://github.com/stevearc/oil.nvim) is an alternative file explorer for Neovim that lets you edit the filesystem inside a normal buffer. The buffer has the type `oil` and is named `oil:///<file path>` (or, I believe, `oil-ssh:///<file path>`, since Oil also has ssh support)

The issue is that since the Oil opens directories in simple buffers, `vim-helm` calls [this function](https://github.com/towolf/vim-helm/blob/69a51170f9e0f7c21242c85e2feac6aa17adeb22/ftdetect/helm.vim#L1-L8) on them (also, I'm not sure why, but `findfile("Chart.yaml", expand('%:p:h').';')` is always returning something, regardless of the current directory being emtpy. i.e. if I'm on an empty `/foo` directory and I call `findfile("Chart.yaml", expand('%:p:h').';')` on it, it will return `/foo/Chart.yaml`)

### Reproducing:
Considering a neovim installation with both `Oil.nvim` and `vim-helm`, and an empty directory `/Users/foo`, when I open that directory with `nvim /Users/foo` and execute:
```vim
:echo findfile("Chart.yaml", expand('%:p:h').';')
```

I see:
![Screenshot 2024-05-21 at 10 44 42](https://github.com/towolf/vim-helm/assets/9031589/9076a60c-55d9-4b09-a9ed-ab4c2e049b0b)
(notice the filetype set to `helm` and the output of the findfile command)

**Comment by luisdavim** [comment]
can you check https://github.com/towolf/vim-helm/pull/26 ?
