### ISSUE TITLE
Improve ftdetect

### ISSUE THREAD

**Issue by rafi** [towolf/vim-helm#7]
Currently there could be collisions with regular yaml files and Ansible yamls, etc.
Also, there's no support for `yml`, only `yaml`.

This can be improved by detecting Chart.yaml in parent directory for example.
Here's an example from an Ansible plugin: https://github.com/pearofducks/ansible-vim/blob/master/ftdetect/ansible.vim

**Comment by towolf** [comment]
So, we also use Ansible and the distinction for us is easy, because our Ansible YAML files have `.yml` and Kubernetes YAMLs have `.yaml`.

But I guess that cannot be a universal distinction.

Detecting Chart.yaml would work but has some drawbacks, i.e. it presupposes a fully formed Helm dir structure.

Want to make a PR for this?

**Comment by towolf** [comment]
In the beginning I did not even include ftdetect at all, because I only wanted to shre the syntax, and not the config. The latter is trickier and subjective. For instance, here's my personal ansibe detection logic:
```
autocmd BufRead,BufNewFile */ansible/*.yml  set ft=yaml.ansible
autocmd BufRead,BufNewFile *.j2,*/ansible/*/templates/* set ft=config.jinja2
```

**Comment by nickjj** [comment]
What if we also included a search on the file contents itself?

Something like this:

```vim
au BufNewFile,BufRead *.{yaml,yml} if getline(1) =~ '^apiVersion:' || getline(2) =~ '^apiVersion:' | setlocal filetype=helm | endif
```

I'm still fairly new to Kubernetes and Helm but isn't it a requirement that a Kubernetes manifest starts with either `---` or `apiVersion:`? That doesn't help us with Chart.yml or values.yml (technically this can have Helm variables in it too right?) but it's one step closer to figuring out what to do without depending on `templates/`?

**Comment by eshepelyuk** [comment]
Hello @nickjj 

1. `---` has nothing to do with k8s, it's just YAML separator for multi document in the single yaml file.
1. But the idea of using `apiVersion` and `kind` - has a very high probability that yaml file contains K8S manifest.

**Comment by nickjj** [comment]
Yes, the `---` is optional. That's why the snippet in my previous comment checks to see if `apiVersion` is the first or second line.

**Comment by dannylongeuay** [comment]
One other idea would be to do a quick check on file contents for any template variables. Search for a pattern, `{{.+}}`, and if found, set file type to helm. You want to make sure you only do this check on specific file types in the first place. I do this on `yaml` file types right now to work around LSP and tree-sitter issues.

**Comment by qRoC** [comment]
For helm_ls:

```
lspconfig.helm_ls.setup {
      filetypes = { "helm", "yaml" },
      on_attach = function(_client, bufnr)
        vim.api.nvim_set_option_value("filetype", "helm", { buf = bufnr })
      end
    }
```

**Comment by luisdavim** [comment]
What about something like:

```vim
function! s:isHelm()
  let filepath = expand("%:p")
  let filename = expand("%:t")
  if filepath =~ '\v/(templates|charts)/.*\.(ya?ml|gotmpl|tpl|txt)$' | return 1 | en
  if filename =~ '\v(helmfile).ya?ml' | return 1 | en
  if getline(1) =~ '^apiVersion:' || getline(2) =~ '^apiVersion:' | return 1 | en
  if !empty(findfile("Chart.yaml", split(filepath,"/")[0].';')) | return 1 | en
  return 0
endfunction

au BufRead,BufNewFile * if s:isHelm() | set ft=helm | en

" Use {{/* */}} as comments
au FileType helm setlocal commentstring={{/*\ %s\ */}}
```
